### ISSUE TITLE
Dat badge

### ISSUE THREAD

**Issue by dcousens** [feross/standard#494]
Suddenly,  it is **huge**.
I mean,  I don't mind much,  but,  it definitely looks a bit obnoxious.

![dayum](https://cloud.githubusercontent.com/assets/413395/14727920/37156ffe-0873-11e6-83d7-717c3dd6d2d3.png)

**Comment by feross** [comment]
Hahaha, will look into that

**Comment by feross** [comment]
Works fine for me: 

<img width="516" alt="screen shot 2016-04-21 at 17 20 15" src="https://cloud.githubusercontent.com/assets/121766/14727962/574eb4a8-07e5-11e6-8a97-6460ebe39027.png">

**Comment by feross** [comment]
I just tried exporting the badge with an explicit size, instead of relying on DPI. Give that page a refresh and let me know if it's better.

**Comment by dcousens** [comment]
@feross interesting.
Happens for me in both Firefox 45.0.2 and Chromium 50.0.2661.75

**Comment by dcousens** [comment]
@feross still occurs.

**Comment by feross** [comment]
Try again?

**Comment by dcousens** [comment]
@feross it happens even when directly linked to the file: https://camo.githubusercontent.com/e06d9d72eecca61c1ba39fdf19868f70fcb3a9b3/68747470733a2f2f63646e2e7261776769742e636f6d2f6665726f73732f7374616e646172642f6d61737465722f62616467652e737667

**Comment by dcousens** [comment]
@feross still nothing,  RE 31254b6

**Comment by feross** [comment]
Fixed

**Comment by dcousens** [comment]
Not fixed here

**Comment by feross** [comment]
I don't know what to tell you. Works for me on ubuntu.

<img width="629" alt="screen shot 2016-04-21 at 17 54 30" src="https://cloud.githubusercontent.com/assets/121766/14728528/87e9e38a-07ea-11e6-9043-62dcdfdc1176.png">

**Comment by feross** [comment]
I reverted the badge change from 6 days ago, so if it worked for you before, then it should be back to that old state again. Badges used to look fine with your setup right?

**Comment by dcousens** [comment]
@feross that they did,  but I have no idea why this is different now.

This occurs on both my Macbook Air and my Arch Linux machine.

**Comment by dcousens** [comment]
ping @fanatid, @jprichardson, @calvinmetcalfe,  any of you three experiencing this?

**Comment by fanatid** [comment]
@dcousens works fine for me
![screenshot at 2016-04-22 07 12 49](https://cloud.githubusercontent.com/assets/2633065/14731515/3ae8e31a-0862-11e6-9de0-2d19f55ff65e.png)
Fedora 23, 64 bit
Firefox 45.0.1
Chrome 50.0.2661.49

**Comment by dcousens** [comment]
@feross @fanatid this is odd.   I have the same issue on my Android device(s) using 4G.
I guess this must be a geolocality issue?

![1mgo7ho](https://cloud.githubusercontent.com/assets/413395/14731650/264639ba-0896-11e6-996e-a1eb0a4b4560.png)
![bncnmvx](https://cloud.githubusercontent.com/assets/413395/14731651/26475908-0896-11e6-88dc-2d1b3d6df78a.png)

**Comment by fanatid** [comment]
@dcousens looks like not geolocality issue, right now on npmjs (on github all looks good):
![screenshot at 2016-04-22 12 30 42](https://cloud.githubusercontent.com/assets/2633065/14737700/838ad642-088e-11e6-83ec-bd30f592bfe4.png)

**Comment by dcousens** [comment]
Ha!  I knew I wasn't crazy.

**Comment by feross** [comment]
Weird. Any ideas?

**Comment by jprichardson** [comment]
Holy big badge batman!

![screen shot 2016-04-22 at 10 01 00 pm](https://cloud.githubusercontent.com/assets/150063/14759171/cb687dd8-08d5-11e6-9ecf-150ad08447e8.png)

**Comment by bencevans** [comment]
Same here, Ubuntu 15.10, Google Chrome Version 49.0.2623.87 (64-bit).

![selection_012](https://cloud.githubusercontent.com/assets/638535/14762425/c2d82f32-0971-11e6-8f03-0e78fc4e9545.png)

Wondered if it was just stuck in GitHub's CDN Cache as when rendered on GitHub it's coming from https://cloud.githubusercontent.com/assets/638535/14762425/c2d82f32-0971-11e6-8f03-0e78fc4e9545.png but the same is happening on npm which loads the badge from https://cdn.rawgit.com/feross/standard/master/badge.svg

Opening https://cdn.rawgit.com/feross/standard/master/badge.svg in the browser I'm getting...

![https --cdn rawgit com-feross-standard-master-badge svg - google chrome_013](https://cloud.githubusercontent.com/assets/638535/14762439/2324e5a6-0972-11e6-8705-7f2296130a7f.png)

**Comment by jprichardson** [comment]
Come on @feross... be honest now, this was your attempt at having Standard take over the world?? 😉

**Comment by feross** [comment]
@jprichardson Yeah, you caught me! 😨 

For real, though. This is so odd. Anyone have any ideas?

**Comment by feross** [comment]
The svg file returned by rawgit is different from the one currently in our repo. I opened an issue to ask them if they can delete the cached version: https://github.com/rgrove/rawgit/issues/111

**Comment by feross** [comment]
This is fixed now!

**Comment by dcousens** [comment]
Hate to be a pain... but this is still happening.
And I cleared all my caches.

**Comment by jprichardson** [comment]
It's fixed for me.

**Comment by dcousens** [comment]
Maybe they didn't flush the Australian CDN?  :shrug:

**Comment by feross** [comment]
I got them to purge the cache once more: https://github.com/rgrove/rawgit/issues/111#issuecomment-215795453

At this point, there's nothing else we can do.
